package com.spo.core_app.Utilities;

import com.spo.core_app.models.globalrecord;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.Random;

@Service
public class SystemUtilities {
    public static void setGlobalRecordValue(globalrecord gr,String createdby,String updatedby,
                                     LocalDateTime createdat,
                                     LocalDateTime updatedat){
        //They are setter methods automatically generated by Lombok because you used @Data.
        gr.setCreatedAt(createdat);
        gr.setCreatedBy(createdby);
        gr.setUpdatedAt(updatedat);
        gr.setUpdatedBy(updatedby);
    }

}
